### ISSUE TITLE
Edit game panel

### ISSUE THREAD

**Issue by shpakvlad** [Uniti-Gaming/admin#20]

**Comment by Bababum95** [comment]
`
import styles from './EditGame.module.scss';
import Heading from '@/components/Heading/Heading.tsx'; //не правильно импортируешь
import classNames from 'classnames';

const EditGame = () => {
    return (
        <div className={styles.editGame}>
            <Heading title='Редактировать игру' size={3}/>

            <div className={styles.content}>
                <label className={styles.label} htmlFor='name'>Название</label>
                <input className={styles.input} type='text' name='name'/>
                //htmlFor так не работает

                <label className={styles.label} htmlFor='link'>Ссылка</label>
                <input className={styles.input} type='text' name='link'/>

                <label className={styles.label} htmlFor='category'>Категория</label>
                <select className={styles.select} name='category' id='category'>
                    <option value='nomoney'>Бесплатно</option>
                    <option value='standartLib'>Стандартная библиотека</option>
                    <option value='extendetLib'>Расширенная библиотека</option>
                </select>
            </div>

            <div className={styles.buttonsPanel}>
                <button className={classNames(styles.button, styles.deleteGameBtn)}>Удалить игру</button>

                <div className={styles.additionalButtons}>
                    <button className={classNames(styles.button, styles.cancelBtn)}>Отмена</button>
                    <button className={classNames(styles.button, styles.saveGameBtn)}>Сохранить изменения</button>
                </div>
            </div>
        </div>
    );
};

export default EditGame;
`

не особо принципиально но старайся простые названия придумывать а не трехэтажные
nomoney - free
cancelBtn - cancel / reset
saveGameBtn - save / submit
deleteGameBtn - delete

и зачем у каждой кнопки свой класс?
нет тега форм
нет типов у кнопок

**Comment by shpakvlad** [comment]
исправил, нет типа у кнопок, можно подробнее?

**Comment by Bababum95** [comment]
`<button type="submit" />`
`<button type="button" />`
если в форме больше 1 кнопки нужны типы, если одна то она будет сабмит

**Comment by shpakvlad** [comment]
Все везде добавил, я просто привык что тип сам ставиться, сейчас я в вебшторме, а там не ставится. Буду внимательнее!!!!
