### ISSUE TITLE
Donut

### ISSUE THREAD

**Issue by shpakvlad** [Uniti-Gaming/admin#22]

**Comment by Bababum95** [comment]
`.donut {
  @include panel;
  padding: 0 16px;
  width: 100%;
  height: 550px;

  display: flex;
  flex-direction: column;
}`
я обновил миксин panel он принимает паддинг

`<div className={styles.donutContent}>`  -  просто content

`                <label className={styles.label}>Название</label>
                <input className={styles.input} type='text'/>

                <label className={styles.label}  htmlFor='game'>Игра</label>
                <input className={styles.input} type='text'/>
`

где то пишешь фор где-то нет
1. либо input обернут в label либо нужен htmlFor
2. htmlFor так не работает
3. input нужен name

`                <div className={styles.buttons}>
                    <button className={classNames(styles.button, styles.unsuccessful)}>Неудачно</button>
                    <button className={classNames(styles.button, styles.pending)}>В обработке</button>
                    <button className={classNames(styles.button, styles.paid)}>Оплачен</button>
                </div>
`

для чего доп классы на кнопках? 


`
            <div className={styles.footerButtons}>
                <button className={styles.button}>Отмена</button>
                <button className={classNames(styles.button, styles.saveButton)}>Сохранить изменения</button>
            </div>
`
просто save или submit. Просто footer


Нет тега form
нет типов у кнопок

**Comment by shpakvlad** [comment]
исправил.
