### ISSUE TITLE
OneUser

### ISSUE THREAD

**Issue by shpakvlad** [Uniti-Gaming/admin#26]
- [x] Исправить верстку
- [x] Исправить роутинг
- [x] Исправить название в хэдере и сайдбаре

## Функционал

- [x] Вывод данных динамический
- [x] Возможность менять данные
- [x] Возможность изменить статус
- [x] Вместо сохранения выводить данные в консоль

**Comment by Bababum95** [comment]
Верстка готова за исключением селектов
